version: "3"
services:
  api:
    container_name: api
    build:
      context: ./api
    depends_on:
      - db
    volumes:
      - ./api:/usr/app
      - /usr/app/node_modules
    environment:
      - MONGO_URL=mongodb://db:27017/todos
      - APP_PORT=80
    ports: ['80:80']

  db:
    container_name: db
    image: mongo:4.0
    restart: always
    ports:
      - '27018:27017'

  ui:
    container_name: ui
    build:
      context: ./ui
    volumes:
      - ./ui:/app
      - /app/node_modules
    ports:
      - '8080:8080'
    environment:
      - BACKEND_URL=http://localhost/todos

